#!/usr/bin/env sh
set -eu

function fake_command() {
  for var in "$@"; do
    mkdir -p "$(dirname "$var")"
    echo 'echo $@' > "$var" && chmod +x "$var"
  done
}

function setup_gitrepo() {
  tempdir=$(mktemp -d)
  cp -r ./test_infra "$tempdir"
  cd "$tempdir/test_infra"
  git init -q
  git add .
  git config --local user.email "test@example.com"
  git config --local user.name "test"
  git commit -q -m "initial commit"
  git clone -q "$(pwd)" ../cloned_infra
  git checkout -q -b other-branch # necessary to allow the cloned repo to push here
  cd ../cloned_infra
  git config --local user.email "test@example.com"
  git config --local user.name "test"
  rm -rf /tmp/artifacts
}

function unset_vars() {
  unset MASTER_REF GIT_BRANCH REPO_NAME
  unset LAYERS MODULES CHANGED_LAYERS
  unset LAYERS_DIR MODULES_DIR WORKING_DIR WORKSPACE_DIR
  unset CIRCLE_BRANCH CIRCLE_SHA1
  unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
  export TF_STATE_BUCKET='test-bucket'
  export TF_STATE_REGION='test-region'
  export TF_STATE_BUCKET_V2='test-bucket-v2'
  export TF_STATE_REGION_V2='test-region-v2'
}
