#!/usr/bin/env sh
set -eu

tag_and_push() {
  docker tag "rackautomation/rackspace-toolbox:$GIT_SHA" "rackautomation/rackspace-toolbox:$1"
  docker tag "rackautomation/rackspace-toolbox:$GIT_SHA" "gcr.io/rs-public-containers/rackspace-toolbox:$1"
  docker push "rackautomation/rackspace-toolbox:$1"
  docker push "gcr.io/rs-public-containers/rackspace-toolbox:$1"
}

GIT_SHA="$1"
TAG=$2
TAG=$(echo "$TAG" | sed 's/\//_/g')

docker pull "rackautomation/rackspace-toolbox:$GIT_SHA"
tag_and_push latest

if (echo "$TAG" | grep -q '[0-9]\+[.][0-9]\+[.][0-9]\+$'); then
  # major.minor.patch
  tag_and_push "$TAG"
  # major.minor
  tag_and_push "$(echo "$TAG" | sed 's/[.][0-9]*$//')"
  # major
  tag_and_push "$(echo "$TAG" | sed 's/[.][0-9]*[.][0-9]*$//')"
else
  tag_and_push "$TAG"
fi
