#!/usr/bin/env sh
set -eu

IMAGE=$(docker build -q -f toolbox/Dockerfile.tests ./toolbox/)

if [ "${1-}" = 'bash' ]; then CMD='bash'; else CMD="bats ./tests"; fi

./scripts/install-drun
./drun \
  -v "$HOME/.ssh:$(pwd)/.ssh:ro" \
  -e TF_STATE_BUCKET='test-bucket' \
  -e TF_STATE_REGION='test-region' \
  "$IMAGE" "$CMD"
