#!/usr/bin/env sh
set -eu

docker build -q -f toolbox/Dockerfile ./toolbox/ -t local/rackspace-toolbox:latest
IMAGE_TEST=$(docker build -q -f toolbox/Dockerfile.tests ./toolbox/)
CMD=${1:-"bats ./tests"}

./scripts/install-drun
./drun \
  -v "$HOME/.ssh:$(pwd)/.ssh:ro" \
  -v "$HOME/.aws:$(pwd)/.aws:ro" \
  -E '^AWS_|^USER$' \
  "$IMAGE_TEST" $CMD
